postgres_host:
    image: postgres:9.4
    env_file:
        - ./docker-base.env
    ports:
        - 49153:5432

app:
    build: ./
    links:
        - postgres_host
    volumes:
        - ./:/opt/app
    env_file:
        - ./docker-base.env
    ports:
        - 3000:3000
        - 8888:8888
